# IF ANY CHANGES ARE MADE TO THIS FILE THE DOCKER CONTAINER ON DOCKERHUB MUST ALSO BE UPDATED WITH THE NEW BUILD!

# USE CODECSNIFFER AS BASE IMAGE

FROM pipelinecomponents/php-codesniffer

# SET THE WORKING DIRECTORY FOR THE CONTAINER

WORKDIR /app

# INCLUDE 'phpcs.xml' IN DOCKER BUILD

COPY phpcs.xml ./phpcs.xml