name: PHPCS Lint                                  # Define the name of the workflow

on: [push, pull_request]                          # Trigger the workflow on push and pull request events

jobs:                                             # Initialise job
  lint:                                           # Define a job named 'lint'
    runs-on: ubuntu-latest                        # Specifies the type of VM to provision

    container:                                    # Initialize container
      image: monkeyknuckles/phpcs                 # Points to PHPCS container

    steps:                                        # List of steps to execute
      - name: Checkout code                       # Checkout code label text
        uses: actions/checkout@v3                 # Use the checkout action to clone the repository

      - name: Copy PHPCS configuration file       # Set PHPCS configuration file label text
        run: cp /app/phpcs.xml $GITHUB_WORKSPACE  # Include the PHPCS configuration file in the docker build
              
      - name: Run Lint PHPCS                      # Set lint PHPCS label text
        run: phpcs --colors --standard=PSR12 .    # Lint all PHP files using a PSR-12 base